# Generated by Django 3.1 on 2021-04-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='isbn',
        ),
    ]
